---
- name: Deploy Web Page to Web Server
  hosts: "{{ web_server }}"
  tasks:

    - name: Ensure proper Apache configuration
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      notify: apache-restart

    - name: Deploy index.html from template
      template:
        src: "./files/index.html"
        dest: /var/www/html/index.html
      notify: apache-restart

  handlers:
    - name: apache-restart
      service:
        name: httpd
        state: restarted
