---
- name: Runs Insights Clients OpenSCAP Scan
  hosts: all
  tasks:
    - name: Installs/Updates OpenSCAP Security Scanning packages
      yum:
        name:
          - scap-security-guide
          - openscap-scanner
          - openscap
        state: latest
        
    - name: Execute Insights CLI
      shell: insights-client --compliance
