---
- name: Runs Insights Clients OpenSCAP Scan
  hosts: all
  tasks:
    - name: Ensure OpenSCAP packages are installed.
      import_playbook: compliance_packages.yml
    - name: Execute Insights CLI
      shell: insights-client --compliance
